// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQrK_g28EZ0haxdkyLwh-2lMMYFZho7vI',
    appId: '1:483306262208:web:fe2bb4ff1a7512220ee725',
    messagingSenderId: '483306262208',
    projectId: 'nobody-flutter-project',
    authDomain: 'nobody-flutter-project.firebaseapp.com',
    storageBucket: 'nobody-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlnCSsjTsj97sI5-9QawWeDjCmrYASA0',
    appId: '1:483306262208:android:b434ebf37060763b0ee725',
    messagingSenderId: '483306262208',
    projectId: 'nobody-flutter-project',
    storageBucket: 'nobody-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6L5T6HsWHUuWx-_mqPEKswGSFso8PE8',
    appId: '1:483306262208:ios:73c54a686a9178a50ee725',
    messagingSenderId: '483306262208',
    projectId: 'nobody-flutter-project',
    storageBucket: 'nobody-flutter-project.appspot.com',
    iosClientId: '483306262208-5v15r0sk55nq609c9tikdmsh4jmhulul.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc6L5T6HsWHUuWx-_mqPEKswGSFso8PE8',
    appId: '1:483306262208:ios:73c54a686a9178a50ee725',
    messagingSenderId: '483306262208',
    projectId: 'nobody-flutter-project',
    storageBucket: 'nobody-flutter-project.appspot.com',
    iosClientId: '483306262208-5v15r0sk55nq609c9tikdmsh4jmhulul.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
